[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_twitter = "3wAuQHUKcPXXRTiPXWBULXm6LALg6v78UjWGbyeQmysp"

[programs.devnet]
solana_twitter = "3wAuQHUKcPXXRTiPXWBULXm6LALg6v78UjWGbyeQmysp"

[programs.mainnet]
solana_twitter = "3wAuQHUKcPXXRTiPXWBULXm6LALg6v78UjWGbyeQmysp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/ahndoro/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p app/src/idl && cp target/idl/solana_twitter.json app/src/idl/solana_twitter.json"
my-custom-script = "echo 'Hello world!'"
